# for local development
version: '3.7'
services:
  quasar:
    build:
      context: .
      target: 'develop-stage2'
    ports:
    - '8080:8080'
    volumes:
    - '.:/my-manager'
    command: /bin/sh -c "quasar dev"
